server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.153.135
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

b2c:
  jwt:
    pubKeyPath: E:/1908/5month/oracle/reskey/rea.pub # 公钥地址
    cookieName: B2C_TOKEN # cookie的名称
