server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.45.205.133:3306/b2c-6?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: Root.123
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  rabbitmq:
    host: 192.168.153.135
    username: b2c
    password: b2c
    virtual-host: b2c
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.mr: debug

