server:
  port: 8089
  
spring:
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.45.205.133:3306/b2c-6?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: Root.123
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  rabbitmq:
    host: 119.45.186.254
    username: b2c
    password: b2c
    virtual-host: b2c
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: b2c.item.exchange
    publisher-confirms: true
  redis:
    host: 119.45.186.254
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: com.mr.item.pojo
  mapper-locations: mapper/OrderMapper.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: mysql
b2c:
  worker:
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: E:/1908/5month/oracle/reskey/rea.pub # 公钥地址
    cookieName: B2C_TOKEN # cookie的名称
